spring:
  datasource:
    url: jdbc:mysql://47.98.149.58:3306/shiro3?characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: gxdmysql!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  #thymeleaf模版前缀
  #thymeleaf:
    #prefix: classpath:/templates/
  redis:
    database: 10
    #host: http://47.98.149.58
    port: 6379
    timeout: 0
    host: http://127.0.0.0

  aop:
    proxy-target-class: true


server:
  port: 8081
